export const data = [
    {
        id: "",
        trackId: "",
        artist: "",
        title: "",
        version: "",
        label: "",
        month: "",
        year: "",
        buyUrl: "",
        votes: "",
        createdAt: "2022-04-12T14:34:00.000Z",
        updatedAt: "",
    },
    {
        id: "",
        trackId: "",
        artist: "",
        title: "",
        version: "",
        label: "",
        month: "",
        year: "",
        buyUrl: "",
        votes: "",
        createdAt: "",
        updatedAt: "",
    },
    {
        id: "",
        trackId: "",
        artist: "",
        title: "",
        version: "",
        label: "",
        month: "",
        year: "",
        buyUrl: "",
        votes: "",
        createdAt: "",
        updatedAt: "",
    },
    {
        id: "",
        trackId: "",
        artist: "",
        title: "",
        version: "",
        label: "",
        month: "",
        year: "",
        buyUrl: "",
        votes: "",
        createdAt: "",
        updatedAt: "",
    },
];
